### ISSUE TITLE
Nginx Start page is all I see

### ISSUE THREAD

**Issue by jleaders** [libresh/compose-nextcloud#13]
Maybe I'm doing something wrong but after I got the containers up and running, and I went to port 80 on the host, I just saw the nginx start page. I know that's from the docker containers because I didn't even have nginx on the host. All I ran was `sudo docker-compose up` from within the git directory

```
Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx.
```

**Comment by jodumont** [comment]
Hi @jleaders 
As I mention in your previous [issue](https://github.com/indiehosters/nextcloud/issues/12)
You probably forget to clone the repo
and you don't have the nginx.conf file

**Comment by pierreozoux** [comment]
Closing as old, and we migrate to another repo https://lab.libreho.st/libre.sh/compose/nextcloud

Feel free to reopen there.
