### ISSUE TITLE
Can't write into config directory!

### ISSUE THREAD

**Issue by comprateur** [libresh/compose-nextcloud#15]
hello, 
I have the a problem with nextcloud after install I have the following message
Can't write into config directory!
Can't write into config directory!
This can usually be fixed by <a href="https://docs.nextcloud.com/server/11/go.php?to=admin-dir_permissions" target="_blank" rel="noreferrer">giving the webserver write access to the config directory</a>.

thanks

**Comment by nikarul** [comment]
I had this same issue on both a Gentoo and CentOS 6 host.  I was able to work around it by entering the app container ("docker exec -it nextcloud_app_1 bash") and from there changing the ownership of the config and data directories to be owned by www-data:www-data ("chown -R www-data:www-data data/ config/").  There's probably a way to automate that permission change but I haven't dug into it yet.

**Comment by ktiedt** [comment]
Tried @nikarul's approach, no luck here... I've tried various combinations of www-data owner or just for testing purposes 777 permissions...

www-data at the root directory results in a redirect loop
www-data at apps and data results in a redirect loop...
777 results in a redirect loop

letting docker create the dirs results in permissions unable to write to config...
clearly there is something amiss with this setup

**Comment by almereyda** [comment]
You can try to review your permissions from outside the container.
I recently had to fix the config folder with the following from within the root of a clone of this repository:

    chmod -R 33:0 data/config

Please note that using the numeric notation brings the help, as the numeric `uid`s and `gid`s can be mapped easily and deterministically.
This is how our working configuration looks like:

```
# ls -lan data/config/
total 15
drwxrwxr-x 2 33 0    5 Nov 23 14:30 .
drwxr-xr-x 6  0 0    6 Jan 11 20:22 ..
-rw-rw-r-- 1 33 0  377 Jun  9  2017 apps.config.php
-rw-r----- 1 33 0 1442 Jan 12 01:44 config.php
```

**Comment by pierreozoux** [comment]
Closing as old, and we migrate to another repo https://lab.libreho.st/libre.sh/compose/nextcloud

Feel free to reopen there.
