### ISSUE TITLE
I can not start, lb_web error

### ISSUE THREAD

**Issue by weyders** [libresh/compose-nextcloud#16]
Hi, when I give the command:
MYSQL_ROOT_PASSWORD=secret docker-compose up
The following error appears:
ERROR: Network lb_web declared as external, but could not be found. Please create the network manually using `docker network create lb_web` and try again.
After creating the lb_web network and running the docker-compose up the error appears:
ERROR: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.1.1:53: read udp 127.0.0.1:54323->127.0.1.1:53 : I / o timeout
And the whole machine loses connection to the internet, only returning when it excludes the created networks of the docker.

**Comment by zhangzheng1212** [comment]
Execute the command ：
docker network create lb_web

**Comment by pierreozoux** [comment]
Sorry for the delay, this is part of http://libre.sh so that's why it doesn't work nicely on its own. If you have ideas to improve that, we welcome feedback :)
