### ISSUE TITLE
Nextcloud url shortening

### ISSUE THREAD

**Issue by mrchrisjoy** [libresh/compose-nextcloud#5]
Hello,

What would be the best way to shorten the URL for Nextcloud?
I want to remove index.php from the url. They provide a video here:
https://www.youtube.com/watch?v=yqr22XG8P4w

I'm wondering if there is something that can be easily done from the container side of things or if I should perform url rewriting on the web proxy.

Thanks

**Comment by pierreozoux** [comment]
Closing as old, and we migrate to another repo https://lab.libreho.st/libre.sh/compose/nextcloud

Feel free to reopen there.
