### ISSUE TITLE
SSL Required. Plain-text http installation fails with redirect-loop.

### ISSUE THREAD

**Issue by projectivemotion** [libresh/compose-nextcloud#9]
After installation on http://<ip>/, the nextcloud container redirects to https://<ip/apps/files/ , which results in browser going nowhere (no error, just spinner keeps spinning.)

Afterwards, refreshing http://<ip>/ the web browser goes into a redirect loop. This time the browser displays the redirect error.

It was only after I created a self-signed certificate and enabled ssl, that I was able to successfully get nextcloud running.

I would like to ask the author to please update the readme to explain that tls is **required** for the container to work properly, and maybe add some instructions about getting a self-signed cert installed with the container.

Here are the steps I followed for [generating self-signed cert:](https://dracoblue.net/dev/https-nginx-with-self-signed-ssl-certificate/)

```
$ mkdir certs
$ cd certs
$ openssl req -new -x509 -nodes -out server.crt -keyout server.key
```

in nginx.conf:
```
   server {
     listen 80;
+    listen              443 ssl;
+    ssl_certificate     /etc/nginx/certs/server.crt;
+    ssl_certificate_key /etc/nginx/certs/server.key;
```

in docker-compose.yml
```
 services:
   web:
     image: nginx
+    ports:
+      - "80:80"
+      - "443:443"
     volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
+      - ./certs:/etc/nginx/certs:ro
```

**Comment by billietl** [comment]
I half-upvote this issue.
I personally handle SSL encryption in my load balancer (which enforce HTTPS by itself), and since I trust my network, I would like my containers to communicate with plain HTTP.
So maybe let the user decide whether they want SSL handled by nginx (and instruct the user how to mount their cert and make nginx listen to port 443) or not (and force nextcloud not to redirect to https) ?

**Comment by jianggau** [comment]
I don't think it is right to use self sign ssl certificate here. 
Because owncloud default redirect http to https. 
So just change the config.php file.

./data/config/config.php
change https to http:  

> 'overwrite.cli.url' => 'http://localhost',  

and set default protocol to http

> 'overwriteprotocol' => 'http',

The redirect issue is gone now.

**Comment by javexed** [comment]
I struggled with this as well... I've written up some instructions on how to use either http or https with some self-signed certs...

**Comment by pierreozoux** [comment]
Closing as old, and we migrate to another repo https://lab.libreho.st/libre.sh/compose/nextcloud

Feel free to reopen there.
